# Use https://dependabot.com/docs/config-file/validator/ to check for errors.
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "./aes-go"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-patch" ]

  - package-ecosystem: "gomod"
    directory: "./tools/client"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-patch" ]

  # Enable version updates for Actions
  - package-ecosystem: "github-actions"
    # Look for `.github/workflows` in the `root` directory
    directory: "/"
    schedule:
      interval: "weekly"
